---
title: "RAI: an R package to calculate relative abundance index from camera-traps"
subtitle: "Package vignette"
author: "Salvador Mandujano R"
date: "Version: `r format(Sys.time())`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RAI}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# General description

The main propose of this package is to provide different functions to calculate the RAIs for the species captured with cameras-traps in the same or different locations and seasons. The `RAI` package was development with few functions that allow automatic store of tables, statistical results, figures and maps. 

# Initial steps

First install the Beta version of the `RAI` package, as:

```
library(devtools)
install_github("SMandujanoR/RAI")
library(RAI)
```

Next create a subdirectory to automatically save the results (tables, graphs, maps, statistical analysis) generated by the different functions, as:

```
dir.create("Results")
```

# Analysis of several species 

### Data

To exemplify the use of the `RAI` package, I selected here a specific data set of 15 medium and large size mammals species and habitat covariates obtained from 24 camera-traps at 1 km of distance in 6000 ha, during wet season of 2018 in the Tehuacán-Cuicatlán Biosphere Reserve in Oaxaca, Mexico. 

### Read data

To estimate RAIs is necessary to load two files: The first is the previously formatted `wildlife_data.csv`, and the second the file contained the covariates of each camera-trap. The first include data of animals organized in four columns: Camera, Species, Events and Effort. Note that in cases where the species was not photographed, is necessary to include 0s in the Events. Read data, as:

```
wildlife_data <- read.csv("Data/mamiferos.csv", header = T)
head(wildlife_data, 25)
```

An important aspect is to keep always the same names of the columns in this `data.frame`:

```
names(wildlife_data)
```

To see the species:

```
unique(wildlife_data$Species)
```

The second `data.frame` contains the UTMs and habitat covariates for each camera-trap, read as:

```
habitat_data <- read.csv("Data/habitat.csv", header = T)
head(habitat_data, 10)
```

Then merge both `data.frames` as:

```
datos <- merge(x = wildlife_data, y = habitat_data, by = "Camera", all = TRUE)
head(datos, 15)

```

This last object (in this example called `datos`) will be used in almost all `RAI` functions.

